build_from:
  aarch64: "homeassistant/aarch64-base:latest"
  amd64: "homeassistant/amd64-base:latest"
  armhf: "homeassistant/armhf-base:latest"
  armv7: "homeassistant/armv7-base:latest"
  i386: "homeassistant/i386-base:latest"
labels:
  org.opencontainers.image.title: "Visa Checker Bot"
  org.opencontainers.image.description: "Schengen vize randevu takip botu - deneme bildirimi sistemi ile"
  org.opencontainers.image.source: "https://github.com/mehmetkahya0/visa-checker"
  org.opencontainers.image.authors: "Mehmet Kahya"
  org.opencontainers.image.licenses: "MIT"
  org.opencontainers.image.version: "1.1.5"
args:
  TEMPIO_VERSION: "2021.09.0"
